```{r}
packrat::on()
library(tidyverse)
library(magrittr)
library(forcats)
library(plotly)
```

```{r}
raw_data <- read_csv("data/printed_data.csv")
color_coordinates <- read_csv("data/crayola_color_coordinates.csv")
  
color_responses <- raw_data %>%
                    select(-starts_with("X")) %>%
                    filter(pilot %in% c('N','n',0)) %>%
                    mutate(stimulus = fct_collapse(stimulus,
                                                 `red` = c("r","41"),
                                                 `purple` = c("pu","57"),
                                                 `pink` = c("pi","13"),
                                                 `white` = c("w","59"),
                                                 `black` = c("bk","4"),
                                                 `orange` = c("o","33"),
                                                 `green` = c("gn","23"),
                                                 `gray` = c("gy","22"),
                                                 `yellow` = c("y","62"),
                                                 `blue` = c("be", "14"),
                                                 `brown` = c("br", "9"))) %>%
                    mutate(response = str_replace_all(response, 
                                      c("^r$" = "red", "^pu$" = "purple", "^pi$" = "pink",
                                      "^w$" = "white", "^bk$" = "black", "^o$" = "orange",
                                      "^gn$" = "green", "^gy$" = "gray", "^y$" = "yellow",
                                      "^be$" = "blue", "^br$" = "brown"))) %>%
                    mutate(response = strsplit(as.character(response), ",")) %>% 
                    unnest(response)

write_csv(color_responses, "data/color_responses.csv", na="")
```


```{r}
phase_2 <- color_responses %>%
  filter(phase == 2) %>%
  group_by(subj) %>%
  mutate(response = as.numeric(as.character(response))) %>%
  left_join(color_coordinates %>% select(id,L,A,B),
            by = c("response" = "id")) %>%
  mutate(L = jitter(L, amount = 0),
         A = jitter(A, amount = 0),
         B = jitter(B, amount = 0))

color_cat_3d <- list()

for (id_num in unique(phase_2$subj)) {
  temp <- filter(phase_2,subj == id_num)
  
  p <- plot_ly(temp, x = ~B, y = ~A, z = ~L, 
                marker = list(color = ~stimulus, colorscale = ~stimulus)) %>%
          layout(scene = list(xaxis = list(title = 'b*'),
                              yaxis = list(title = 'a*'),
                              zaxis = list(title = 'L*')))
  color_cat_3d[[id_num]] <- p
  
}


```

